GET http://localhost:3001/api/users/

###

POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "email": "test2@gmail.com",
    "password": "test2"
}

###

PUT http://localhost:3000/api/auth/change-password
content-type: application/json

{
    "oldPassword": "test3",
    "newPassword": "test2"
}